### PR TITLE
Make polymer dependency compatible with all versions until 1.0.0

### PR DESCRIPTION
**Pull request by zenorocha**
This is a kind of practice the all polymer projects are adopting...

See: https://github.com/Polymer/core-ajax/commit/bcfadab for example

### CODE REVIEW

**Comment by janantala** [comment]
Merged, thx @zenorocha

**Comment by zenorocha** [comment]
Could you tag a new version of it?

**Comment by janantala** [comment]
Done https://github.com/janantala/love-heart/releases/tag/v0.3.0

**Comment by zenorocha** [comment]
:)

**Pull request merged**
